* 110 - THERMOS Wiki

This is a deployment of the STEEP Stakeholder engagement platform.

See the master branch readme.org for what the various STEEP components do.

See the gla-smart-energy branch readme.org for deployment instructions and known issues.

It should run for as long as the THERMOS project. Talk to Martin Holley before shutting it down.

** Live Server

Hosted on bolt.r.cse.org.uk:/pool/nixops-config/1110-thermos-wiki. Access at https://wiki.thermos-project.eu.

Backed up daily to bolt.r.cse.org.uk:/thermos-wiki.

** Credentials

The following are available in the CSE password database:
 + Wiki login for a user with admin permissions
 + HTTP Basic password

Database passwords are not needed.

** Database

Uses PostgreSQL instead of MySQL. In hindsight, this is a mistake: Mediawiki is much better tested with MySQL.

** Differences from GLA Smart Energy Wiki

Replaced the London logo with the THERMOS logo.

Removed some items from the main menu.

Added the [[https://www.mediawiki.org/wiki/Extension:MsCalendar][MsCalendar extension]].

** Known Issues

These are in addition to those listed in the readme of the gla-smart-energy branch.

*** MsCalendar Localization

This is correct in some places, but in others it makes a mess.
