* 737 - London Smart Energy Wiki

This is a deployment of the STEEP Stakeholder engagement platform.

See the master branch for the main readme contents.

It is owned by Simon Roberts at CSE. He is responsible for deciding how long it should live.

** Live Server

Hosted using NixOps on bolt.r.cse.org.uk:/pool/nixops-config/737-gla-smart-energy-wiki, it can be accessed at https://london-smart-energy.cse.org.uk/wiki.

Backed up daily onto bolt.r.cse.org.uk:/pool/backup/gla-wiki.

** Credentials

The following are available in the CSE password database:
 + MySQL root password
 + MySQL mediawiki password
 + HTTP basic password for user 'london'

** Nix Compatibility

For this project, we replaced our deployment / upgrade scripts with a NixOps definition. This is much more reliable / reusable.

** Build Process

To create a wiki using this code:
 + Create a passwords file (see instructions in machines.nix)
 + Deploy with NixOps
 + =nixops ssh gla-wiki=
 + Create users with the =mediawiki-main-createAndPromote= command.

** Known Issues
*** TODO Update to NixPkgs 17.09

It was deployed with 16.09.

*** TODO Tidy up Parsoid definition

There is a custom Nix definition in the parsoid folder. We should replace this with a version from NixPkgs.

*** TODO Tidy up Mediawiki definition

There is a custom Nix definition mediawiki.nix. The only change I've made is to add extra PHP scripts to the /mediawikiScripts/ property.

We should revert back to using the standard package from NixPkgs. If we still want the extra scripts, we should add them with a small override to the package instead of duplicating it.

After that, we should review our config files (anything in this folder ending in .php).

*** TODO STEEP Maps and Process Models don't work with Nix

I didn't do the work to adapt these to work with Nix.

If we decided to resurrect these, then we have the problem that the ShareJS project is dead. This means that the whole backend (which includes collaborative live editing) would have to be replaced.

** Differences from STEEP

We're using newer versions of things than STEEP:
 + Mediawiki 1.27.1 instead of 1.25.1
 + PHP 7.0.16 instead of 5.6.17
 + MariaDB 10.1.21 instead of MySQL 5.5.46

We've dropped the following extensions:
 + STEEP Projects extension
 + STEEP Map and Process Model extensions
 + Semantic Mediawiki, Semantic Forms, Semantic Drilldown
 + R (no longer maintained)
 + Interwiki (now built in)
 + Graphviz
 + InputBox (now built in)
 + ElasticSearch and CirrusSearch

The things from STEEP that we are still using are:
 + The skin and icons
 + CategoryTables

We've replaced the EU and STEEP logos with London logos.
