* Steep Mediawiki Gadgets
Adds buttons to Mediawiki's Visual Editor to allow you to insert a [[https://github.com/cse-bristol/process-model][Process Model]] or [[https://github.com/cse-bristol/energy-efficiency-planner][Map]].

Part of the Stakeholder Engagement Platform for the [[http://www.smartsteep.eu/][Steep Project]].

[[https://github.com/cse-bristol/share-server][Code]] distributed under an open source MIT license.

See: [[https://doc.wikimedia.org/VisualEditor/master/][Visual Editor API]], [[http://www.mediawiki.org/wiki/Manual:Tag_extensions/Example][Tag Extensions Example]].

** Future Plans
*** Pointing to existing documents
From the Visual Editor, I'd like to change which document a process-model is pointing at, or remove it.

** Dependencies
 * Mediawiki v1.24.0.
 * [[http://www.mediawiki.org/wiki/Extension:VisualEditor][VisualEditor]] REL1_24 branch.
 * [[https://github.com/wikimedia/parsoid][Parsoid]] (with a running Parsoid server). Not that this does not require the Parsoid extension be installed into Mediawiki.
 * The Process Model and Map software hosted on the same domain as your wiki. Set up and run a [[https://github.com/cse-bristol/share-server][ShareJS Server]] to act as the backend for these.

The Steep Project also uses [[https://semantic-mediawiki.org/][Semantic Mediawiki]], but we do not actually require that for these components.

Verify your Mediawiki plugins by looking at the Special:Version page of your wiki.

** Deployment
Run the following from inside your Mediawiki directory:
#+BEGIN_SRC
# Checkout the code into the extensions folder.
git clone git@github.com:cse-bristol/steep-mediawiki-gadgets.git extensions/steep-mediawiki-gadgets

# Modify LocalSettings.PHP
echo 'require_once "$IP/extensions/steep-mediawiki-gadgets/steep-mediawiki-gadgets.php";' >> LocalSettings.php
#+END_SRC
